# example of a machine specific settings
windows:
  mainwindow:
    provider: custom_probebasic:CustomProbeBasic
    kwargs:
      confirm_exit: false

data_plugins:
  tooltable:
    provider: qtpyvcp.plugins.tool_table:ToolTable
    kwargs:
        columns: TZDUR

  offsettable:
    provider: qtpyvcp.plugins.offset_table:OffsetTable
    kwargs:
      columns: "XYZR"

  file_locations:
    provider: qtpyvcp.plugins.file_locations:FileLocations
    log_level: debug
    kwargs:
      default_location: Users
      local_locations:
        # format: Location Name: path
        Users: ~/linuxcnc/nc_files/USERS
      network_locations:

settings:

  # VTK backplot view settings

  backplot.show-grid:
    default_value: true

  backplot.show-program-bounds:
    default_value: true

  backplot.show-program-labels:
    default_value: false

  backplot.show-program-ticks:
    default_value: false

  backplot.show-machine-bounds:
    default_value: true

  backplot.show-machine-labels:
    default_value: false

  backplot.show-machine-ticks:
    default_value: false

  backplot.perspective-view:
    default_value: false

  backplot.view:
    default_value: 5
    options: ["X: Front View",
              "Y: Front View",
              "Z: Top View",
              "Z2: Bottom View",
              "P: Isometric",
              "M: Machine EXT"]

  backplot.machine-ext-scale:
    default_value: 0.4

  backplot.multitool-colors:
    default_value: True

  backplot.show-machine-model:
    default_value: false
